package cn.imustacm.heartbeat.utils;

import java.util.Random;

import cn.imustacm.heartbeat.R;

/**
 * 项目名：HeartBeat
 * 包名：cn.imustacm.heartbeat.utils
 * 文件名：RandomUtils
 * 描述：随机数据工具类
 */

public class RandomUtils {

    public static String[] names = {
            "Enid Henry", "Mildred Marion", "Eden Margery", "Jeff Zechariah", "Berg Ingersoll", "Emma Robin", "Jesse Maurice", "Yvonne Huntington", "Oswald Richard", "Mignon Laurie", "Stephanie Mackintosh", "Jason Herty", "Steven Cowper", "Arlen Kingsley", "Tim Benson", "Felix Chaucer", "Payne Will", "Cliff Stowe", "Vera ", "Porter Crofts", "Jocelyn Malachi", "Alston Cromwell", "Jacob Aly", "Elmer Reed", "Gary Galbraith", "Todd Hughes", "Rebecca Lattimore", "Eunice Occam", "Renata Adelaide", "Miles III.", "Eden Arthur", "Cornelia Anna", "Jessica Jenny", "Vito Leacock", "Novia Gabriel", "Franklin Ernest", "Rachel Acheson", "Thomas Longfellow", "Ingemar Flynn", "Hermosa Tommy", "Page Middleton", "Clement Bray", "Coral Lewis", "Brady Leigh", "Maria Simon", "Oliver Edgeworth", "Lou Newton", "Ann Joyce", "Darcy Hosea", "Jennifer Noah", "Bblythe O'Connor", "Asa Bill", "Cornelius Harold", "Xaviera Ann", "Tina Lily", "Simon Hodge", "Noel Ruskin", "Tab Nancy", "Vicky Palmer", "Muriel Guy", "Ruby Hope", "Lawrence Walker", "Grace Service", "Hogan Jeremiah", "Gale Francis", "Mag Parker", "Rod Richardson", "Kim Goldsmith", "Ula Victor", "Quintina Morley", "Mandel Benjamin", "Calvin Johnny", "Jo Lucius", "Miranda Susan", "Jeremy Bloomfield", "Irma Jerome", "Neil Wilhelmina", "York Violet", "Mike Ford", "Adair Wesley", "Marina Gilbert", "Greg Jane", "Janice Romeo", "Lynn Martha", "Astrid Giles", "Alan Twain", "Bard David", "Basil Edmund", "Oscar Beerbohm", "Evelyn Carey", "Antonia Maggie", "Edwiin Garcia", "Andrea Carrie", "Lennon Clara", "Philip Grey", "Chad Gard(i)ner", "Ted Saroyan", "Kevin Johnson", "Broderick Kitto", "Glenn Hornby", "Kristin Beard", "Jonathan Gosse", "Merry Gladstone", "Myra Raman", "Yves Jackson", "Colin Kipling", "Marjorie Micah", "Esther Mac-", "Odelette Augustine", "Cara Norris", "Evan Wallis", "Tracy O'Neil", "Sarah Grote", "Myron Collins", "Murray Moore", "Moses Mansfield", "Marsh Matthew", "Joanne Dorothea", "Uriah Thackeray", "Sherry Leighton", "Lucien Vincent", "Archer Sheridan", "Venus Patrick", "Ralap Brook", "Bridget Belloc", "Lisa Steinbeck", "Max Malan", "Barnett Wat",
            "Morton Stephens", "Meredith Julius", "Roy Charles", "Melissa Daniel", "Sean Felix", "Roderick Juliana", "Eleanore Barrie", "Leona Curme", "Elliot Byron", "Violet Hawthorne", "Colbert Cotton", "Claude Sam", "Denise Milton", "Winston Jeremy", "Rosemary Smedley", "Joshua Adam", "Ulysses Martin", "Juliet Evan", "Rock Louis", "Elvira Katharine", "Dolores Morse", "Sylvia Peacock", "Letitia Browne", "Martina Hicks", "Amy Melville", "Shirley Masefield", "Bowen Dewey", "Hobart Bert", "Odelia Eliot", "Josephine Maugham", "Len Betsy", "Ida Hudson", "Sid Camilla", "Ingrid Lancelot", "Barret Doyle", "Olga Halifax", "Clare Congreve", "Burke Pigou", "Dinah Locke", "Parker Craigie", "Isaac Perkin", "Francis Ezekiel", "Rita Ralph", "Caesar Vaughan", "Hunter Edison", "Teresa Toland", "Carey Andrew", "Mandy Thodore", "Kent Bulwer", "Clark Kit", "Will Gibson", "Olive O'Casey", "Jerome Polly", "Armstrong Joel", "Ian MacPherson", "Kama Effie", "Joseph Stella", "Blake Childe", "Sandy McCarthy", "Marlon ", "Cornell Gold", "Dale Poe", "Judith Rosa", "Suzanne Huxley", "Bonnie Windsor", "Alfred Nicholas", "Merlin Strachey", "Taylor Jack", "Molly Tyler", "Cleveland Adams", "Cheryl Dewar", "Eric Rockefeller", "Valentina Turner", "Reginald Grace", "Gabrielle Armstrong", "Aaron I.", "Joyce Roosevelt", "Yetta Boyle", "Beverly Benedict", "Ira Moll", "Duke Swift", "Magee Adolph", "Aubrey Mat(h)ilda", "Valerie Hobbes", "Lorraine Philip", "Orville Robinson", "Hazel Lucas", "Jean Walkley", "Frances Maxwell", "Barlow Peter", "Fay Tracy", "Sampson Jones", "Ruth Sandy", "Nathaniel Carllyle", "Merle Toby", "Byron Maria", "Evangeline Tate", "Lindsay Cissie", "Dempsey Bruce", "Ellis Wilde", "Dominic Lyly", "Milo Dryden", "Geraldine Holmes", "Laurel Constance", "Cecil Donne", "Georgia Alsop(p)", "Helen Bunyan", "Hannah Thompson", "Douglas Zacharias", "Osborn Becky", "Janet Alice", "Andy Newman", "Octavia Jimmy", "Lucy Brewster", "Lena Bloomer", "Ernest Bloor", "Ivan Defoe", "Ford Mary", "Chasel Bartholomew", "Maurice Bradley", "Jill Whitman", "Sebastian Carl", "Godfery Croft", "Jodie ", "Katherine Ulysses", "Albert Hutt", "Booth Trollpoe", "Tracy Nehemiah",
            "Tom Priestley", "Dunn Pullman", "Toby Nathaniei", "Debby Field", "Emily Sawyer", "Spencer Lambert", "Bruno Rutherford", "Daniel Barton", "Alberta Rhodes", "Blithe Dickey", "Clara Wheeler", "Elijah Agnes", "Jo Bethune", "Lauren Morgan", "Bernard Watt", "Leopold Harrod", "Bart Becher", "Pete Ted", "Malcolm Dalton", "Carter Henrietta", "Alvis Christopher", "Elsa Herbert", "Jerry Wodehous", "Leo Macadam", "Anna Samuel", "Zara Eveline", "April Black", "Mona Virginia", "Archibald Duncan", "Curitis Lou(ie)", "Patricia Dodd", "Eudora DuBois", "Natividad Peg", "May Pound", "Lester Commons", "Deborah Jean", "Quintion Dunbar", "Tobey ", "Sabrina Clarissa", "Fabian Blake", "Don Bob", "Rupert Felton", "Blanche Stone", "Erin Taylor", "Belle Michelson", "Bob Dolly", "Judy James", "Isidore Wolf", "Harriet Salome", "Fitch Noyes", "Olivia Smith", "Dennis Nico(l)", "Alger Johnston(e)", "Doreen Nell", "Edith Tom", "Donahue Sherwood", "Clyde Saul", "Belinda Berkeley", "Beau Charlotte", "Honey Price", "Quinn Philemon", "Beacher Sinclair", "Mamie Walter", "Haley Camp", "Dick MacArthur", "Carl Augustus", "Buck MacMillan", "Yale Bronte", "Hayden Zephaniah", "Elaine Pullan", "Hiram Wollaston", "Salome Isaac", "Mirabelle May", "Daisy Nahum", "Ivy Strong", "Cathy Lawson", "Paula Stevenson", "Roxanne Clemens", "Joanna Whittier", "Larry Eddie", "Atwood Thomas", "Xanthe Morton", "Bernie Pepys", "Yehudi Jacob", "Rose Catharine", "Maxwell Cumberland", "Alma Geoffrey", "Virgil Anne", "Bruce Peggy", "Kelly Bessemer", "Nicola Esther", "Constance Hamlet", "Blair Lizzie", "Sebastiane Gregory", "Elvis Bryce", "Sharon Keynes", "Jim Ruth", "Tiffany Elizabeth", "Harold Woolf", "Kennedy Marcellus", "Willie Law", "Ina Hume", "Crystal McDonald", "Gloria Barrett", "Gerald Antonia", "Griselda Clapham", "Werner Thorndike", "Julia Bowman", "Victor Gus", "Herman Child", "Setlla Stuart", "Jared Bell", "Winifred Hansom", "Nat Habakkuk", "Elma Davy", "Jack Lawrence", "Grover Albert", "Genevieve Walton", "Derrick Harvey", "Hilary Surrey", "Leif Webster", "Sophia II.", "Natalie Garden", "Jay Boswell", "Wanda Dickens", "Sigrid Robeson", "Stanford Dutt", "Lillian Kent",
            "Jenny Bellamy", "Tammy Cook(e)", "Otto Owen", "Mavis Shaw", "Paddy Bess", "Christine Tuttle", "Walter Sophy", "Jessie Ellen", "Deirdre Foster", "Arlene Godwin", "Justin Susanna", "Bella Judson", "Christian Sally", "Ursula Kell(e)y", "Valentine Marner", "Nancy Helin(a)", "Baird Webb", "Samantha Hobson", "Ingram Malory", "Chester Emerson", "Truda Hood", "Dwight Scott", "Horace Hubbard", "Veromca Truman", "Michelle Austen", "Darlene Irving", "Ethel Houston", "Virginia Ella", "Poppy Lincoln", "Gladys Clark(e)", "Amanda Rose", "Fanny Raymond", "Jane Snow", "Dorothy Frances", "Rae Cronin", "Cynthia Ramsden", "Catherine Jenkin(s)", "Carol Eugen", "Warner Austin", "Jamie Petty", "Andrew Hal", "Vita Wilmot(t)", "Marvin Moulton", "Lyndon Wright", "Cash Rayleign", "Antonio Haywood", "Randolph Judd", "Tyrone Hamilton", "Borg Bennett", "Alexander Reade", "Gwendolyn Jonson", "Barry Mill", "Veronica Church", "Mary Woolley", "Winfred Kennedy", "Upton Pritt", "Cecilia Bush", "Lance Yale", "Armand Buckle", "Hugh Walsh", "George Jeames", "Pamela Lucia", "Benedict Daisy", "Bill Temple", "Rory Alfred", "Linda Dobbin", "Lesley Connor", "Bernice Coffey", "Celeste Symons", "Myrna Baker", "Angela Edith", "Griffith Gaskell", "Abigail Jonathan", "Prudence Nelson", "Queena Monroe", "Benjamin Mond", "Candice Ivan", "Wright More", "Ophelia Samson", "Norton Bartlett", "Edison Burns", "Amos Shakespeare", "Marcus Juliet", "Nicholas Van", "Christ Bessie", "Nydia Elsie", "Wade Carpenter", "Spring Luke", "Kenneth Christy", "Una Hansen", "Sam Keats", "Anastasia Young", "Ives Robert", "Abraham Henley", "Solomon Hardy", "Wendell Bernal", "Alice Tours", "Everley Finger", "Simona Joule", "Selena Huggins", "Hedy Dupont", "Vivien Lindberg(h)", "Arthur Tony", "Hamiltion Pitman", "Gordon Christie", "Elroy Pater", "Channing Daniell", "Jonas Jasper", "Chapman Hazlitt", "Zebulon Eleanor", "Enoch Hoover", "Hilary Sander", "Conrad Birrell", "Ada Orlando", "Monica Valentine", "Truman Eden", "Joan Cocker", "Dominic Morris", "Verna Dierser", "Caroline Bird", "Baron Terry", "Ben MacAdam", "Doris Tobias", "Ken Patience", "Otis Macaulay", "Liz Morrison", "Tabitha Humphr(e)y", "Raymond Doris",
            "Troy Frederick", "Herbert Harriman", "Robert Reynolds", "Allen Chapman", "Modesty Addison", "Eve Rusk", "Drew Rebecca", "Adonis Russell", "Diana Penn", "Hedda MacDonald", "Elizabeth Simpson", "Richard Wallace", "Ed John", "Adolph Caroline", "Megan Aldington", "Marguerite Barney", "Owen Jonah", "Phoebe Cecillia", "Bertha Crichton", "Matthew Gunter", "Pearl Rossetti", "Kay Shelley", "Xenia Bowen", "Hilda Whitehead", "Gemma Louisa", "Joy Delia", "Ron Judith", "Boris Evans", "Kitty Rosalind", "Maureen Wyld(e)", "Hugo George", "Marcia Warner", "Giles Nixon", "Reg Lew", "Donna Marcus", "Wendy Gresham", "Ronald Roy", "Michael Scripps", "Faithe Wild", "Martin Hugh", "Madeline Christian", "Hulda Bentham", "Moore Electra", "Erica Beaufort", "Norman Euphemia", "Antony Warren", "Wilbur Harte", "Noah Ricardo", "Madge Nora", "Charles Hodgson", "Kimberley Wyclif(fe)", "Renee Browning", "Murphy Tomlinson", "Sibyl Gibbon", "Stanley Saxton", "Burgess Darwin", "Julius Forster", "Thera Isaiah", "Eartha Eva", "Phil Gallup", "Barton Wordsworth", "Hyman Beck", "Nigel Brown", "Betsy Kelvin", "Rachel Harrington", "Charlotte Faraday", "Ferdinand Carter", "Trista Wyat(t)", "Adela Madge", "Bishop Broad", "Morgan Green", "Edward Galsworthy", "Luther DeQuincey", "Norma Mark", "Michaelia Zangwill", "Devin Harrison", "Penny Rhys", "Sandra Tout", "Nelson Longman", "Florence Babbitt", "Gabriel Sharp", "Mortimer Connie", "Louis Funk", "Nicole Burne-Jones", "Ward Joan", "Bevis Mike", "Bing Bertha", "Vic Winifred", "Omar Meg", "Bartholomew Edie", "Levi Tennyson", "Camille Minnie", "Jacqueline Gunther", "James Belle", "August Christ", "Augus Lee", "Ella Yule", "Delia Dorothy", "Benson Moses", "Gustave Marshall", "Mabel Howell(s)", "Dylan Spenser", "Wallis Colclough", "Carr Noel", "Rex Partridge", "Peter Thoreau", "John Joshua", "Maud Washington", "William Amelia", "Martha Louise", "Tony Wheatley", "Sandy Carnegie", "Frederica Chaplin", "Angelo Isabel", "Dave Pollitt", "Verne Abraham", "Harry Anderson", "Dean Jim", "Gustave Finn", "Hardy William", "Laura Fred", "June Frank", "Eugene Thomson", "Riva Gray", "Lee Rob", "Yedda IV.", "Christopher Maltz", "Frank Carmen",
            "Afra Katte", "Corey Richards", "Harley Emma", "Ternence Smollett", "Xavier Hart", "Colby Arabella", "Jeffrey Johnson", "Viola Barnard", "Donald Sidney", "Penelope Milne", "Arvin Pulitzer", "Freda Obadiah", "Stacey Hopkin(s)", "Phoenix Sara(h)", "Zoe Gill", "Tess Josh", "Sheila Katrine", "Vivian Geordie", "Edmund Hoyle", "Lynn Southey", "Moira Sonmerfield", "Ryan Churchill", "Iris Bridges", "Page Toynbee", "Bradley FitzGerald", "Victoria Yerkes", "Quentin Charley", "Woodrow Raphael", "Bess Motley", "Leila Clare", "Alexia Murray", "Wordsworth Whit", "Flora Steele", "Mark Sophia", "Amelia Bernard", "Phyllis Joe", "Aldrich Whyet", "Gill Clement", "Theresa Eve", "Nina Archibald", "Ogden Dunlop", "Edwina Hill", "Howar Coleridge", "Bert Rudolph", "Gene Veblen", "Kerr Kellogg", "Nora Graham", "Brian Lowell", "Zachary Eipstein", "Edgar Horace", "Zenobia Lynd", "Isabel Bart", "Susie Wilcox", "Rudolf Pope", "Lewis Yeates", "Humphrey Waters", "Monroe Dillon", "Keith Faulkner", "Gilbert Pansy", "Guy Marjory", "Beck Dora", "Beatrice Howard", "Arno Leopold", "Betty Emmie", "Burton Conan", "Aurora Gracie", "Dana Onions", "Bennett Malthus", "Beryl Stilwell", "Gail Ward", "Brandon Fielding", "Kirk Spencer", "Darren Sassoon", "Perry Silas", "Yvette Coverdale", "Berton Kelsen", "Robin Franklin", "Marshall Abe", "Scott Fowler", "Bertram Hemingway", "Julian Piers", "Cyril Lytton", "Athena Bertram", "Augustine Springhall", "Quincy Fast", "Elva Dan", "Nick Cooper", "Audrey Bruno", "Susanna Ferdinand", "Frederic Pearson", "Marian Nelly", "Annabelle Norton", "Barbara Stephen", "Walker Sainsbury", "Gregary Powell", "Adam ", "Roberta Bauer", "Dawn Emily", "Agatha Haydn", "Nelly Alcott", "Prima Den(n)is", "Dora Yonng", "Burnell Lena", "Cora Arnold", "Lambert Sweet", "Adelaide North", "Webb ", "Stan Vogt", "Tyler Alick", "Maggie Sapir", "Cedric Julian", "Paul Christiana", "Zero Wood", "Brook Margaret", "Dana Adela", "Vincent Horatio", "Hubery Elinor", "Eli Trevelyan", "Tiffany Raglan", "Meroy ", "Rosalind Brooke", "Abner Job", "Michell Holt", "Egbert Betty", "Kelly Evelina", "Regan Housman", "Alva Sailsbury", "Claire Bright",
            "Newman Gallacher", "Gavin Jessie", "Emmanuel Marlowe", "Samuel Chamberlain", "Elsie Hearst", "King Theresa", "Rodney Joseph", "Primo Harry", "Maxine Kitty", "Avery Jennings", "Chloe Roland", "Baldwin Harper", "Theobald Wilson", "Boyd Alerander", "Matt Paul", "Nathan Bobby", "Polly Bertie", "Boyce Chesterton", "Clarence Max", "Cherry Landon", "Lilith Titus", "Andre Quiller", "Wayne Gissing", "Leonard Conrad", "Patrick Eugene", "Webster Lloyd", "Daphne Lamb", "Sara Bacon", "Eileen Ben", "Lydia Kathleen", "Susan Flower", "Vanessa Raleign", "Heloise Edward", "Harvey Hewlett", "Abbott Bryan", "Agnes Aled(k)", "Winni Burke", "Theodore Antoinette", "Zora Keppel", "Saxon Jefferson", "Montague Carroll", "Geoffrey Spender", "Miriam Walpole", "Regina Dulles", "Zona Oliver", "Abel Cook", "Alvin Wells", "Aries Anthony", "Pag London", "Kyle Timothy", "Sidney Attlee", "Sally Buck", "Mick Haggai", "Karen Doherty", "Louise Maud", "Duncan Aldridge", "Julie Julia", "Elton Fox", "Kerwin Copperfield", "Alva Lucy", "Sabina Ferguson", "Harlan Ellis", "Pandora Michael", "Steward House", "Henry Montgomery", "Marico Lindsay", "David Leonard", "Joyce Back", "Les Nichol(s)", "Ansel Wagner", "Hale Lynch", "Earl Ackerman(n)", "Irene Meredith", "Lionel Douglas(s)", "Darnell Fanny", "Abel Dryden", "Verna Dupont", "Frederica Mond", "Linda Gregory", "Jerry Larkin", "Ivan Strong", "Greg Micah", "Joseph Tracy", "Hubery Simon", "Lisa Raman", "Mildred Ted", "Hunter David", "Jane Palmer", "Ira Polly", "Violet Monroe", "Kelly Smollett", "Winston Tommy", "Setlla Franklin", "Daniel Warren", "Gladys Wilde", "Albert Margaret", "Nigel Harry", "Coral Darwin", "Victor Stilwell", "Amy Frances", "Ted Baldwin", "Pag Nico(l)", "Joyce Lew", "Tina Judith", "Enoch Julius", "Perry Camilla", "Gale Edie", "Gwendolyn Bulwer", "Richard Goldsmith", "Rae Elizabeth", "Janice Chamberlain", "Barlow Fowler", "Howar Connor", "Payne Reed", "Patricia Rosalind", "Gill Ricardo", "Renata Hobson", "Miles Galbraith", "Buck Dewar", "Hale Frederick", "Faithe Thackeray", "Belle Lynch", "Doris Cecillia", "Alfred Ben", "Poppy Crofts", "Zoe Robert", "Nicole Wesley", "Daphne Young",
            "Kyle Giles", "Honey Oscar", "Hedy Ruth", "Lucy Hearst", "Sherry Richard", "Spring Ward", "Mark Sonmerfield", "Cornell Grey", "Phoebe Fred", "Rock Marcus", "Teresa Jonah", "Giles Hoyle", "Sebastiane Pigou", "Angela Masefield", "Geraldine Field", "Samuel Temple", "Grover Michelson", "Earl Hill", "Cecil Bryce", "Griffith Judson", "Natividad Yerkes", "Anastasia Thomson", "Herman Gallacher", "Geoffrey Jeames", "Otto Roosevelt", "Marvin Lee", "Cynthia Maurice", "Roberta Pollitt", "Nydia Ferguson", "Yehudi Burns", "Sibyl Ernest", "Levi Silas", "Rosalind Tours", "Parker Haydn", "Pandora Eden", "Sandra Houston", "Vera Baker", "Valentina Nell", "Alva Pansy", "Bertha Child", "Colbert Hawthorne", "Elma Bess", "Wade Grote", "Abner Whittier", "Kristin Robbins", "Renee Smedley", "Cyril Romeo", "Curitis Buck", "Paul Broad", "Barnett Godwin", "Sharon Dan", "Len Cronin", "Xanthe Tout", "Pete Nelson", "Jerome Collins", "Winni Back", "Molly Sophy", "Hamiltion Moses", "Gary Aldington", "Maxine Warner", "Martina North", "Luther Willard", "Chasel Johnson", "Alan Bowman", "Jo Bach", "Ron Eleanor", "Ulysses Coverdale", "Barry Ulysses", "Quincy Gilbert", "Noel Cook", "Steward Gissing", "Dylan Jane", "Sandy Piers", "George Rayleign", "Hobart Laurie", "Ed Moore", "Kerr Graham", "Phil Black", "Glenn Wilmot(t)", "Kennedy Toby", "Duncan Chaplin", "William Bellamy", "Hogan Eve", "Susanna Antoinette", "Madge Steele", "Humphrey Sally", "Dean Yeates", "Oliver Bacon", "Olga Rob", "Sidney Finger", "Wordsworth Symons", "Jodie Jasper", "Claude Keynes", "Burnell Bell", "Bard MacDonald", "Dinah Robinson", "Phyllis Emerson", "Gloria Macaulay", "Letitia Walter", "Bblythe Rossetti", "Abbott Wyclif(fe)", "Lucien Robeson", "Joanna Moll", "Winifred Shelley", "Tom Needham", "Veronica Huggins", "Valerie Reynolds", "Sabina Lincoln", "Michaelia Oliver", "Horace More", "Les Stephens", "Ann Montgomery", "Sean Lancelot", "Crystal FitzGerald", "Omar Bryan", "Angelo Cissie", "Berg Henry", "Tabitha Pitman", "Lilith Newman", "Robert Humphr(e)y", "Aaron Eliot", "Mag Effie", "Carr Winifred", "Ella Juliana", "Julia Acheson", "Truda Marlowe", "Maxwell Elsie", "Jeffrey Wilson",
            "Vincent Benedict"
    };

    public static Integer[] cardImages = {
            R.drawable.card_image_1, R.drawable.card_image_2, R.drawable.card_image_3, R.drawable.card_image_4, R.drawable.card_image_5, R.drawable.card_image_6, R.drawable.card_image_7, R.drawable.card_image_8,
            R.drawable.card_image_9, R.drawable.card_image_10, R.drawable.card_image_11, R.drawable.card_image_12, R.drawable.card_image_13, R.drawable.card_image_14, R.drawable.card_image_15, R.drawable.card_image_16,
            R.drawable.card_image_17, R.drawable.card_image_18, R.drawable.card_image_19, R.drawable.card_image_20, R.drawable.card_image_21, R.drawable.card_image_22, R.drawable.card_image_23, R.drawable.card_image_24,
            R.drawable.card_image_25, R.drawable.card_image_26, R.drawable.card_image_27, R.drawable.card_image_28, R.drawable.card_image_29, R.drawable.card_image_30, R.drawable.card_image_31, R.drawable.card_image_32,
            R.drawable.card_image_33, R.drawable.card_image_34, R.drawable.card_image_35, R.drawable.card_image_36, R.drawable.card_image_37, R.drawable.card_image_38, R.drawable.card_image_39, R.drawable.card_image_40,
            R.drawable.card_image_41, R.drawable.card_image_42, R.drawable.card_image_43, R.drawable.card_image_44, R.drawable.card_image_45, R.drawable.card_image_46, R.drawable.card_image_47, R.drawable.card_image_48,
            R.drawable.card_image_49, R.drawable.card_image_50, R.drawable.card_image_51, R.drawable.card_image_52, R.drawable.card_image_53, R.drawable.card_image_54, R.drawable.card_image_55, R.drawable.card_image_56,
            R.drawable.card_image_57, R.drawable.card_image_58, R.drawable.card_image_59, R.drawable.card_image_60, R.drawable.card_image_61, R.drawable.card_image_62, R.drawable.card_image_63, R.drawable.card_image_64,
            R.drawable.card_image_65, R.drawable.card_image_66, R.drawable.card_image_67, R.drawable.card_image_68, R.drawable.card_image_69, R.drawable.card_image_70, R.drawable.card_image_71, R.drawable.card_image_72,
            R.drawable.card_image_73, R.drawable.card_image_74, R.drawable.card_image_75, R.drawable.card_image_76, R.drawable.card_image_77, R.drawable.card_image_78, R.drawable.card_image_79, R.drawable.card_image_80,
            R.drawable.card_image_81, R.drawable.card_image_82, R.drawable.card_image_83, R.drawable.card_image_84, R.drawable.card_image_85, R.drawable.card_image_86, R.drawable.card_image_87, R.drawable.card_image_88,
            R.drawable.card_image_89, R.drawable.card_image_90, R.drawable.card_image_91, R.drawable.card_image_92, R.drawable.card_image_93, R.drawable.card_image_94, R.drawable.card_image_95, R.drawable.card_image_96
    };

    public static Integer[] headImages = {
            R.drawable.head_image_1, R.drawable.head_image_2, R.drawable.head_image_3, R.drawable.head_image_4, R.drawable.head_image_5, R.drawable.head_image_6, R.drawable.head_image_7, R.drawable.head_image_8, R.drawable.head_image_9, R.drawable.head_image_10, R.drawable.head_image_11, R.drawable.head_image_12, R.drawable.head_image_13, R.drawable.head_image_14, R.drawable.head_image_15, R.drawable.head_image_16,
            R.drawable.head_image_17, R.drawable.head_image_18, R.drawable.head_image_19, R.drawable.head_image_20, R.drawable.head_image_21, R.drawable.head_image_22, R.drawable.head_image_23, R.drawable.head_image_24, R.drawable.head_image_25, R.drawable.head_image_26, R.drawable.head_image_27, R.drawable.head_image_28, R.drawable.head_image_29, R.drawable.head_image_30, R.drawable.head_image_31, R.drawable.head_image_32,
            R.drawable.head_image_33, R.drawable.head_image_34, R.drawable.head_image_35, R.drawable.head_image_36, R.drawable.head_image_37, R.drawable.head_image_38, R.drawable.head_image_39, R.drawable.head_image_40, R.drawable.head_image_41, R.drawable.head_image_42, R.drawable.head_image_43, R.drawable.head_image_44, R.drawable.head_image_45, R.drawable.head_image_46, R.drawable.head_image_47, R.drawable.head_image_48,
            R.drawable.head_image_49, R.drawable.head_image_50, R.drawable.head_image_51, R.drawable.head_image_52, R.drawable.head_image_53, R.drawable.head_image_54, R.drawable.head_image_55, R.drawable.head_image_56, R.drawable.head_image_57, R.drawable.head_image_58, R.drawable.head_image_59, R.drawable.head_image_60, R.drawable.head_image_61, R.drawable.head_image_62, R.drawable.head_image_63, R.drawable.head_image_64,
            R.drawable.head_image_65, R.drawable.head_image_66, R.drawable.head_image_67, R.drawable.head_image_68, R.drawable.head_image_69, R.drawable.head_image_70, R.drawable.head_image_71, R.drawable.head_image_72, R.drawable.head_image_73, R.drawable.head_image_74, R.drawable.head_image_75, R.drawable.head_image_76, R.drawable.head_image_77, R.drawable.head_image_78, R.drawable.head_image_79, R.drawable.head_image_80,
            R.drawable.head_image_81, R.drawable.head_image_82, R.drawable.head_image_83, R.drawable.head_image_84, R.drawable.head_image_85, R.drawable.head_image_86, R.drawable.head_image_87, R.drawable.head_image_88, R.drawable.head_image_89, R.drawable.head_image_90, R.drawable.head_image_91, R.drawable.head_image_92, R.drawable.head_image_93, R.drawable.head_image_94, R.drawable.head_image_95, R.drawable.head_image_96,
            R.drawable.head_image_97, R.drawable.head_image_98, R.drawable.head_image_99, R.drawable.head_image_100, R.drawable.head_image_101, R.drawable.head_image_102, R.drawable.head_image_103, R.drawable.head_image_104
    };

    public static Integer[] timeLineImages = {
            R.drawable.timeline_image_1, R.drawable.timeline_image_2, R.drawable.timeline_image_3, R.drawable.timeline_image_4, R.drawable.timeline_image_5, R.drawable.timeline_image_6, R.drawable.timeline_image_7, R.drawable.timeline_image_8,
            R.drawable.timeline_image_9, R.drawable.timeline_image_10, R.drawable.timeline_image_11, R.drawable.timeline_image_12, R.drawable.timeline_image_13, R.drawable.timeline_image_14, R.drawable.timeline_image_15, R.drawable.timeline_image_16,
            R.drawable.timeline_image_17, R.drawable.timeline_image_18, R.drawable.timeline_image_19, R.drawable.timeline_image_20, R.drawable.timeline_image_21, R.drawable.timeline_image_22, R.drawable.timeline_image_23, R.drawable.timeline_image_24,
            R.drawable.timeline_image_25, R.drawable.timeline_image_26, R.drawable.timeline_image_27, R.drawable.timeline_image_28, R.drawable.timeline_image_29, R.drawable.timeline_image_30, R.drawable.timeline_image_31, R.drawable.timeline_image_32,
            R.drawable.timeline_image_33, R.drawable.timeline_image_34, R.drawable.timeline_image_35, R.drawable.timeline_image_36, R.drawable.timeline_image_37, R.drawable.timeline_image_38, R.drawable.timeline_image_39, R.drawable.timeline_image_40,
            R.drawable.timeline_image_41, R.drawable.timeline_image_42, R.drawable.timeline_image_43, R.drawable.timeline_image_44, R.drawable.timeline_image_45, R.drawable.timeline_image_46, R.drawable.timeline_image_47, R.drawable.timeline_image_48
    };

    // 获取随机用户名
    public static String getRandomName() {
        Random random = new Random();
        return names[random.nextInt(names.length)];
    }
    // 获取随机卡片图片
    public static Integer getRandomCardImage() {
        Random random = new Random();
        return cardImages[random.nextInt(cardImages.length)];
    }
    // 获取随机头像图片
    public static Integer getRandomHeadImage() {
        Random random = new Random();
        return headImages[random.nextInt(headImages.length)];
    }

    // 获取随机时间轴背景图片
    public static Integer getRandomTimeLineImage() {
        Random random = new Random();
        return timeLineImages[random.nextInt(timeLineImages.length)];
    }
}
